"""[REQ:BA-07] Phase-0 running-sim smoke gate (host-side artifact half): the bringup_smoke launch composes the
gz_sim seam (gz + robot_state_publisher + spawn + gz_bridge) PLUS RViz (stewie_rviz/mission.rviz) + rosbag2
recording of the AS-01 contract topics, and the container smoke (deploy/ros2/ba07_smoke.sh) drives /cmd_vel
and asserts the contract topics publish, the rover MOVES into the bag, RViz loads, and truth stays truth-denied.
The running-sim half is container-verified (deploy/ros2/evidence/_smoke_ba07.txt); truth-denial of the bridge
itself is proven by [REQ:AS-06] test_gz_bridge.py."""
import os

import yaml

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
_LAUNCH = os.path.join(_ROOT, "ros2_ws", "src", "stewie_bringup", "launch", "bringup_smoke.launch.py")
_SMOKE = os.path.join(_ROOT, "deploy", "ros2", "ba07_smoke.sh")
_RVIZ = os.path.join(_ROOT, "ros2_ws", "src", "stewie_rviz", "rviz", "mission.rviz")
_EVIDENCE = os.path.join(_ROOT, "deploy", "ros2", "evidence", "_smoke_ba07.txt")


def _read(p: str) -> str:
    with open(p, encoding="utf-8") as fh:
        return fh.read()


def test_ba07_bringup_smoke_launch_composes_gz_rviz_and_bag():  # [REQ:BA-07]
    src = _read(_LAUNCH)
    assert "gz_sim.launch.py" in src                       # the gz + rsp + spawn + gz_bridge seam
    assert "rviz2" in src and "mission.rviz" in src         # RViz on the mission config
    assert '"bag"' in src and '"record"' in src             # rosbag2 recording
    for t in ("/stewie/imu", "/stewie/wheel_odom", "/stewie/perception/points", "/stewie/truth/pose", "/cmd_vel"):
        assert t in src, f"bringup_smoke does not record {t}"


def test_ba07_smoke_asserts_topics_move_bag_and_truth_denial():  # [REQ:BA-07]
    s = _read(_SMOKE)
    assert "/cmd_vel" in s and "MOVE OK" in s               # drives cmd_vel + asserts real motion
    assert "ros2 bag info" in s and "BAG OK" in s           # asserts the bag recorded
    assert "truth/pose" in s and "TRUTH OK" in s            # truth-denial (separate channel)
    for t in ("/stewie/imu", "/stewie/wheel_odom", "/stewie/perception/points", "/stewie/camera/front_left/image"):
        assert t in s, f"the smoke does not assert {t} publishes"


def test_ba07_mission_rviz_shows_robot_map_costmap_path():  # [REQ:BA-07]
    cfg = yaml.safe_load(_read(_RVIZ))
    assert "Visualization Manager" in cfg
    classes = _read(_RVIZ)
    for disp in ("RobotModel", "Path", "Map", "PointCloud2", "Odometry"):
        assert disp in classes, f"mission.rviz missing the {disp} display (RS-05/BA-07 evidence view)"


def test_ba07_container_smoke_evidence_recorded():  # [REQ:BA-07]
    # the container-verified running-sim smoke leaves its captured stdout here (regenerated by ba07_smoke.sh
    # in the stewie-gazebo container); its presence + SMOKE OK marker is the evidence the running sim passed.
    assert os.path.exists(_EVIDENCE), "run deploy/ros2/ba07_smoke.sh in the stewie-gazebo container"
    assert "SMOKE OK: BA-07" in _read(_EVIDENCE)
