// GENERATED by scripts/gen_ts_api_client.py from the FastAPI OpenAPI -- DO NOT EDIT BY HAND.
// Regenerate with `python scripts/gen_ts_api_client.py`; CI (--check) reds on drift.


export type ApiPath =
  | '/admin/backup/replicate'
  | '/admin/gates/validate'
  | '/admin/invite'
  | '/admin/operators'
  | '/admin/operators/approve'
  | '/admin/operators/create'
  | '/admin/operators/reset'
  | '/admin/operators/revoke'
  | '/admin/operators/role'
  | '/admin/operators/{email}'
  | '/admin/trash/missions'
  | '/admin/trash/missions/{filename}'
  | '/admin/twin/retention'
  | '/admin/twin/snapshot'
  | '/auth/config'
  | '/auth/invite/redeem'
  | '/auth/login'
  | '/auth/logout'
  | '/auth/me'
  | '/auth/password'
  | '/auth/register'
  | '/bodies.json'
  | '/cesium/{path}'
  | '/clasts/scene'
  | '/compare'
  | '/config'
  | '/config/full'
  | '/construction'
  | '/contracts/schema'
  | '/dem/asbuilt'
  | '/dem/georef'
  | '/dem/heightfield'
  | '/dem/site_lonlat'
  | '/dem/site_xy'
  | '/dem/sources'
  | '/dem/terrain_grid'
  | '/dem/workarea.png'
  | '/dem/{name}'
  | '/draft'
  | '/edit/session'
  | '/edit/session/{sid}'
  | '/edit/session/{sid}/audit'
  | '/edit/session/{sid}/keepout'
  | '/edit/session/{sid}/keepout/{fid}'
  | '/edit/session/{sid}/marker'
  | '/edit/session/{sid}/marker/{fid}'
  | '/edit/session/{sid}/undo'
  | '/ephemeris'
  | '/events'
  | '/evidence'
  | '/evidence/bundle'
  | '/executive/advance'
  | '/executive/audit'
  | '/executive/release-plan'
  | '/executive/run'
  | '/executive/run/{run_id}'
  | '/executive/run/{run_id}/stream'
  | '/export/cog/available'
  | '/export/cog/{kind}.tif'
  | '/export/geojson'
  | '/fleet'
  | '/fonts/{name}'
  | '/gis/import'
  | '/gis/mission-package'
  | '/gis/query'
  | '/icons/{name}'
  | '/index.html'
  | '/landing'
  | '/landing.html'
  | '/layers'
  | '/layers/globe/{kind}.png'
  | '/layers/globe/{kind}/bbox'
  | '/layers/legend'
  | '/layers/raster/{kind}.png'
  | '/library'
  | '/library/{atype}/{aid}'
  | '/library/{atype}/{aid}/export'
  | '/library/{atype}/{aid}/recover'
  | '/localize'
  | '/localize/render'
  | '/localize/traverse'
  | '/missions'
  | '/missions/{name}'
  | '/missions/{name}/publish'
  | '/missions/{name}/restore'
  | '/models'
  | '/nav/contract'
  | '/nav/executive'
  | '/nav/faults'
  | '/nav/local_plan'
  | '/nav/react'
  | '/nav/run'
  | '/ogc/wms'
  | '/perception/depth-sources'
  | '/physics/authority'
  | '/physics/backends'
  | '/physics/compatibility'
  | '/physics/terramechanics-spine'
  | '/plan'
  | '/plan/commands'
  | '/plan/math'
  | '/profile'
  | '/profile/{name}'
  | '/profiles'
  | '/program'
  | '/program/snapshot'
  | '/rc/command'
  | '/rc/eligibility'
  | '/rc/plan_ros'
  | '/rc/ros_odom'
  | '/rc/telemetry'
  | '/rc/telemetry/stream'
  | '/render'
  | '/render/parallax'
  | '/resync/compare'
  | '/ros/evidence'
  | '/ros/export/costmap'
  | '/ros/export/occupancy'
  | '/ros/export/path'
  | '/runtime/profiles'
  | '/sample_mission/{name}'
  | '/sample_missions'
  | '/sense'
  | '/session/start'
  | '/session/{sid}/debrief'
  | '/session/{sid}/divergence'
  | '/session/{sid}/operator'
  | '/session/{sid}/scorecard'
  | '/session/{sid}/summary'
  | '/siteplan/analyze'
  | '/siteplan/volume'
  | '/sites'
  | '/slam'
  | '/slam/compare'
  | '/soil/{name}'
  | '/soils'
  | '/solar'
  | '/structure'
  | '/structures/custom'
  | '/structures/custom/{name}'
  | '/structures/custom/{name}/expand'
  | '/tiles/{name}/{asset}'
  | '/trainer/history'
  | '/twin/cg'
  | '/twin/history'
  | '/twin/resync'
  | '/twin/terrain/{site}'
  | '/twin/version'
  | '/world'
  | '/world/layer-catalog'
  | '/world/layer-consumption'
  | '/world/layer-manifest'
  | '/world/point'
  | '/world/points'
  | '/world/site-markers'
  | '/world/terrain_view'
  | '/world/terrain_view.png'
  | '/world/terramechanics-layers'
  | '/world/traffic-layer'
  | '/world/transaction'
  | '/world/transactions'
  | '/world/transect'
  | '/{path}';

export interface ApiRoute {
  readonly method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  readonly path: ApiPath;
  readonly operationId: string;
  readonly mutatesAuthority: boolean;
}

export const API_ROUTES: readonly ApiRoute[] = [
  { method: 'POST', path: '/admin/backup/replicate', operationId: 'admin_replicate_admin_backup_replicate_post', mutatesAuthority: true },
  { method: 'POST', path: '/admin/gates/validate', operationId: 'admin_gates_admin_gates_validate_post', mutatesAuthority: true },
  { method: 'POST', path: '/admin/invite', operationId: 'invite_mint_admin_invite_post', mutatesAuthority: true },
  { method: 'GET', path: '/admin/operators', operationId: 'operators_list_admin_operators_get', mutatesAuthority: false },
  { method: 'POST', path: '/admin/operators/approve', operationId: 'operators_approve_admin_operators_approve_post', mutatesAuthority: true },
  { method: 'POST', path: '/admin/operators/create', operationId: 'operators_create_admin_operators_create_post', mutatesAuthority: true },
  { method: 'POST', path: '/admin/operators/reset', operationId: 'operators_reset_password_admin_operators_reset_post', mutatesAuthority: true },
  { method: 'POST', path: '/admin/operators/revoke', operationId: 'operators_revoke_admin_operators_revoke_post', mutatesAuthority: true },
  { method: 'POST', path: '/admin/operators/role', operationId: 'operators_set_role_admin_operators_role_post', mutatesAuthority: true },
  { method: 'DELETE', path: '/admin/operators/{email}', operationId: 'operators_delete_admin_operators__email__delete', mutatesAuthority: true },
  { method: 'GET', path: '/admin/trash/missions', operationId: 'mission_trash_admin_trash_missions_get', mutatesAuthority: false },
  { method: 'DELETE', path: '/admin/trash/missions/{filename}', operationId: 'mission_purge_admin_trash_missions__filename__delete', mutatesAuthority: true },
  { method: 'POST', path: '/admin/twin/retention', operationId: 'admin_retention_admin_twin_retention_post', mutatesAuthority: true },
  { method: 'POST', path: '/admin/twin/snapshot', operationId: 'admin_snapshot_admin_twin_snapshot_post', mutatesAuthority: true },
  { method: 'GET', path: '/auth/config', operationId: 'auth_config_auth_config_get', mutatesAuthority: false },
  { method: 'POST', path: '/auth/invite/redeem', operationId: 'invite_redeem_auth_invite_redeem_post', mutatesAuthority: true },
  { method: 'POST', path: '/auth/login', operationId: 'auth_login_auth_login_post', mutatesAuthority: true },
  { method: 'POST', path: '/auth/logout', operationId: 'auth_logout_auth_logout_post', mutatesAuthority: true },
  { method: 'GET', path: '/auth/me', operationId: 'auth_me_auth_me_get', mutatesAuthority: false },
  { method: 'POST', path: '/auth/password', operationId: 'auth_set_password_auth_password_post', mutatesAuthority: true },
  { method: 'POST', path: '/auth/register', operationId: 'auth_register_auth_register_post', mutatesAuthority: true },
  { method: 'GET', path: '/bodies.json', operationId: 'get_bodies_bodies_json_get', mutatesAuthority: false },
  { method: 'GET', path: '/cesium/{path}', operationId: 'get_cesium_cesium__path__get', mutatesAuthority: false },
  { method: 'GET', path: '/clasts/scene', operationId: 'clasts_scene_clasts_scene_get', mutatesAuthority: false },
  { method: 'POST', path: '/compare', operationId: 'post_compare_compare_post', mutatesAuthority: true },
  { method: 'GET', path: '/config', operationId: 'get_config_config_get', mutatesAuthority: false },
  { method: 'GET', path: '/config/full', operationId: 'get_config_full_config_full_get', mutatesAuthority: false },
  { method: 'GET', path: '/construction', operationId: 'get_construction_construction_get', mutatesAuthority: false },
  { method: 'GET', path: '/contracts/schema', operationId: 'contracts_schema_contracts_schema_get', mutatesAuthority: false },
  { method: 'POST', path: '/dem/asbuilt', operationId: 'dem_asbuilt_dem_asbuilt_post', mutatesAuthority: true },
  { method: 'GET', path: '/dem/georef', operationId: 'dem_georef_dem_georef_get', mutatesAuthority: false },
  { method: 'GET', path: '/dem/heightfield', operationId: 'dem_heightfield_dem_heightfield_get', mutatesAuthority: false },
  { method: 'GET', path: '/dem/site_lonlat', operationId: 'dem_site_lonlat_dem_site_lonlat_get', mutatesAuthority: false },
  { method: 'GET', path: '/dem/site_xy', operationId: 'dem_site_xy_dem_site_xy_get', mutatesAuthority: false },
  { method: 'GET', path: '/dem/sources', operationId: 'dem_sources_catalog_dem_sources_get', mutatesAuthority: false },
  { method: 'GET', path: '/dem/terrain_grid', operationId: 'dem_terrain_grid_route_dem_terrain_grid_get', mutatesAuthority: false },
  { method: 'GET', path: '/dem/workarea.png', operationId: 'dem_workarea_png_dem_workarea_png_get', mutatesAuthority: false },
  { method: 'GET', path: '/dem/{name}', operationId: 'get_dem_dem__name__get', mutatesAuthority: false },
  { method: 'GET', path: '/draft', operationId: 'draft_load_draft_get', mutatesAuthority: false },
  { method: 'PUT', path: '/draft', operationId: 'draft_save_draft_put', mutatesAuthority: true },
  { method: 'POST', path: '/edit/session', operationId: 'create_session_edit_session_post', mutatesAuthority: true },
  { method: 'GET', path: '/edit/session/{sid}', operationId: 'get_session_edit_session__sid__get', mutatesAuthority: false },
  { method: 'GET', path: '/edit/session/{sid}/audit', operationId: 'get_audit_edit_session__sid__audit_get', mutatesAuthority: false },
  { method: 'POST', path: '/edit/session/{sid}/keepout', operationId: 'create_keepout_edit_session__sid__keepout_post', mutatesAuthority: true },
  { method: 'DELETE', path: '/edit/session/{sid}/keepout/{fid}', operationId: 'delete_keepout_edit_session__sid__keepout__fid__delete', mutatesAuthority: true },
  { method: 'PATCH', path: '/edit/session/{sid}/keepout/{fid}', operationId: 'modify_keepout_edit_session__sid__keepout__fid__patch', mutatesAuthority: true },
  { method: 'POST', path: '/edit/session/{sid}/marker', operationId: 'create_marker_edit_session__sid__marker_post', mutatesAuthority: true },
  { method: 'DELETE', path: '/edit/session/{sid}/marker/{fid}', operationId: 'delete_marker_edit_session__sid__marker__fid__delete', mutatesAuthority: true },
  { method: 'POST', path: '/edit/session/{sid}/undo', operationId: 'undo_edit_edit_session__sid__undo_post', mutatesAuthority: true },
  { method: 'GET', path: '/ephemeris', operationId: 'ephemeris_ephemeris_get', mutatesAuthority: false },
  { method: 'GET', path: '/events', operationId: 'get_events_events_get', mutatesAuthority: false },
  { method: 'GET', path: '/evidence', operationId: 'get_evidence_evidence_get', mutatesAuthority: false },
  { method: 'GET', path: '/evidence/bundle', operationId: 'evidence_bundle_evidence_bundle_get', mutatesAuthority: false },
  { method: 'POST', path: '/executive/advance', operationId: 'advance_executive_executive_advance_post', mutatesAuthority: true },
  { method: 'GET', path: '/executive/audit', operationId: 'executive_audit_executive_audit_get', mutatesAuthority: false },
  { method: 'POST', path: '/executive/release-plan', operationId: 'release_plan_executive_release_plan_post', mutatesAuthority: true },
  { method: 'POST', path: '/executive/run', operationId: 'executive_run_executive_run_post', mutatesAuthority: true },
  { method: 'GET', path: '/executive/run/{run_id}', operationId: 'executive_run_get_executive_run__run_id__get', mutatesAuthority: false },
  { method: 'GET', path: '/executive/run/{run_id}/stream', operationId: 'executive_run_stream_executive_run__run_id__stream_get', mutatesAuthority: false },
  { method: 'GET', path: '/export/cog/available', operationId: 'export_cog_available_export_cog_available_get', mutatesAuthority: false },
  { method: 'GET', path: '/export/cog/{kind}.tif', operationId: 'export_value_cog_export_cog__kind__tif_get', mutatesAuthority: false },
  { method: 'GET', path: '/export/geojson', operationId: 'export_geojson_export_geojson_get', mutatesAuthority: false },
  { method: 'GET', path: '/fleet', operationId: 'get_fleet_fleet_get', mutatesAuthority: false },
  { method: 'GET', path: '/fonts/{name}', operationId: 'get_font_fonts__name__get', mutatesAuthority: false },
  { method: 'POST', path: '/gis/import', operationId: 'gis_import_gis_import_post', mutatesAuthority: true },
  { method: 'GET', path: '/gis/mission-package', operationId: 'gis_mission_package_gis_mission_package_get', mutatesAuthority: false },
  { method: 'POST', path: '/gis/query', operationId: 'gis_query_gis_query_post', mutatesAuthority: true },
  { method: 'GET', path: '/icons/{name}', operationId: 'get_icon_icons__name__get', mutatesAuthority: false },
  { method: 'GET', path: '/index.html', operationId: 'get_index_index_html_get', mutatesAuthority: false },
  { method: 'GET', path: '/landing', operationId: 'landing_page_landing_get', mutatesAuthority: false },
  { method: 'GET', path: '/landing.html', operationId: 'landing_page_landing_html_get', mutatesAuthority: false },
  { method: 'GET', path: '/layers', operationId: 'get_layers_layers_get', mutatesAuthority: false },
  { method: 'GET', path: '/layers/globe/{kind}.png', operationId: 'globe_layer_png_layers_globe__kind__png_get', mutatesAuthority: false },
  { method: 'GET', path: '/layers/globe/{kind}/bbox', operationId: 'globe_layer_bbox_layers_globe__kind__bbox_get', mutatesAuthority: false },
  { method: 'GET', path: '/layers/legend', operationId: 'layers_legend_layers_legend_get', mutatesAuthority: false },
  { method: 'GET', path: '/layers/raster/{kind}.png', operationId: 'get_raster_layer_layers_raster__kind__png_get', mutatesAuthority: false },
  { method: 'GET', path: '/library', operationId: 'library_list_library_get', mutatesAuthority: false },
  { method: 'GET', path: '/library/{atype}/{aid}', operationId: 'library_inspect_library__atype___aid__get', mutatesAuthority: false },
  { method: 'GET', path: '/library/{atype}/{aid}/export', operationId: 'library_export_library__atype___aid__export_get', mutatesAuthority: false },
  { method: 'POST', path: '/library/{atype}/{aid}/recover', operationId: 'library_recover_library__atype___aid__recover_post', mutatesAuthority: true },
  { method: 'POST', path: '/localize', operationId: 'post_localize_localize_post', mutatesAuthority: true },
  { method: 'POST', path: '/localize/render', operationId: 'post_localize_render_localize_render_post', mutatesAuthority: true },
  { method: 'GET', path: '/localize/traverse', operationId: 'get_localize_traverse_localize_traverse_get', mutatesAuthority: false },
  { method: 'GET', path: '/missions', operationId: 'mission_list_missions_get', mutatesAuthority: false },
  { method: 'DELETE', path: '/missions/{name}', operationId: 'mission_delete_missions__name__delete', mutatesAuthority: true },
  { method: 'GET', path: '/missions/{name}', operationId: 'mission_load_missions__name__get', mutatesAuthority: false },
  { method: 'POST', path: '/missions/{name}', operationId: 'mission_save_missions__name__post', mutatesAuthority: true },
  { method: 'POST', path: '/missions/{name}/publish', operationId: 'mission_publish_missions__name__publish_post', mutatesAuthority: true },
  { method: 'POST', path: '/missions/{name}/restore', operationId: 'mission_restore_missions__name__restore_post', mutatesAuthority: true },
  { method: 'GET', path: '/models', operationId: 'get_models_models_get', mutatesAuthority: false },
  { method: 'GET', path: '/nav/contract', operationId: 'get_nav_contract_nav_contract_get', mutatesAuthority: false },
  { method: 'POST', path: '/nav/executive', operationId: 'post_executive_nav_executive_post', mutatesAuthority: true },
  { method: 'POST', path: '/nav/faults', operationId: 'post_faults_nav_faults_post', mutatesAuthority: true },
  { method: 'POST', path: '/nav/local_plan', operationId: 'post_local_plan_nav_local_plan_post', mutatesAuthority: true },
  { method: 'POST', path: '/nav/react', operationId: 'post_react_nav_react_post', mutatesAuthority: true },
  { method: 'POST', path: '/nav/run', operationId: 'post_nav_run_nav_run_post', mutatesAuthority: true },
  { method: 'GET', path: '/ogc/wms', operationId: 'wms_ogc_wms_get', mutatesAuthority: false },
  { method: 'GET', path: '/perception/depth-sources', operationId: 'depth_sources_perception_depth_sources_get', mutatesAuthority: false },
  { method: 'GET', path: '/physics/authority', operationId: 'get_physics_authority_physics_authority_get', mutatesAuthority: false },
  { method: 'GET', path: '/physics/backends', operationId: 'get_physics_backends_physics_backends_get', mutatesAuthority: false },
  { method: 'GET', path: '/physics/compatibility', operationId: 'get_physics_compatibility_physics_compatibility_get', mutatesAuthority: false },
  { method: 'GET', path: '/physics/terramechanics-spine', operationId: 'get_terramechanics_spine_physics_terramechanics_spine_get', mutatesAuthority: false },
  { method: 'POST', path: '/plan', operationId: 'post_plan_plan_post', mutatesAuthority: true },
  { method: 'POST', path: '/plan/commands', operationId: 'plan_commands_plan_commands_post', mutatesAuthority: true },
  { method: 'POST', path: '/plan/math', operationId: 'plan_math_endpoint_plan_math_post', mutatesAuthority: true },
  { method: 'POST', path: '/profile', operationId: 'post_profile_profile_post', mutatesAuthority: true },
  { method: 'GET', path: '/profile/{name}', operationId: 'get_profile_profile__name__get', mutatesAuthority: false },
  { method: 'GET', path: '/profiles', operationId: 'get_profiles_profiles_get', mutatesAuthority: false },
  { method: 'GET', path: '/program', operationId: 'program_page_program_get', mutatesAuthority: false },
  { method: 'GET', path: '/program/snapshot', operationId: 'program_snapshot_program_snapshot_get', mutatesAuthority: false },
  { method: 'POST', path: '/rc/command', operationId: 'rc_command_rc_command_post', mutatesAuthority: true },
  { method: 'GET', path: '/rc/eligibility', operationId: 'rc_eligibility_rc_eligibility_get', mutatesAuthority: false },
  { method: 'POST', path: '/rc/plan_ros', operationId: 'rc_plan_ros_rc_plan_ros_post', mutatesAuthority: true },
  { method: 'POST', path: '/rc/ros_odom', operationId: 'rc_ros_odom_rc_ros_odom_post', mutatesAuthority: true },
  { method: 'GET', path: '/rc/telemetry', operationId: 'rc_telemetry_rc_telemetry_get', mutatesAuthority: false },
  { method: 'GET', path: '/rc/telemetry/stream', operationId: 'rc_telemetry_stream_rc_telemetry_stream_get', mutatesAuthority: false },
  { method: 'POST', path: '/render', operationId: 'post_render_render_post', mutatesAuthority: true },
  { method: 'POST', path: '/render/parallax', operationId: 'post_render_parallax_render_parallax_post', mutatesAuthority: true },
  { method: 'POST', path: '/resync/compare', operationId: 'resync_compare_resync_compare_post', mutatesAuthority: true },
  { method: 'GET', path: '/ros/evidence', operationId: 'get_ros_evidence_ros_evidence_get', mutatesAuthority: false },
  { method: 'POST', path: '/ros/export/costmap', operationId: 'post_export_costmap_ros_export_costmap_post', mutatesAuthority: true },
  { method: 'POST', path: '/ros/export/occupancy', operationId: 'post_export_occupancy_ros_export_occupancy_post', mutatesAuthority: true },
  { method: 'POST', path: '/ros/export/path', operationId: 'post_export_path_ros_export_path_post', mutatesAuthority: true },
  { method: 'GET', path: '/runtime/profiles', operationId: 'get_runtime_profiles_runtime_profiles_get', mutatesAuthority: false },
  { method: 'GET', path: '/sample_mission/{name}', operationId: 'get_sample_mission_sample_mission__name__get', mutatesAuthority: false },
  { method: 'GET', path: '/sample_missions', operationId: 'get_sample_missions_sample_missions_get', mutatesAuthority: false },
  { method: 'POST', path: '/sense', operationId: 'post_sense_sense_post', mutatesAuthority: true },
  { method: 'POST', path: '/session/start', operationId: 'session_start_session_start_post', mutatesAuthority: true },
  { method: 'GET', path: '/session/{sid}/debrief', operationId: 'session_debrief_session__sid__debrief_get', mutatesAuthority: false },
  { method: 'GET', path: '/session/{sid}/divergence', operationId: 'session_divergence_session__sid__divergence_get', mutatesAuthority: false },
  { method: 'GET', path: '/session/{sid}/operator', operationId: 'session_operator_session__sid__operator_get', mutatesAuthority: false },
  { method: 'GET', path: '/session/{sid}/scorecard', operationId: 'session_scorecard_session__sid__scorecard_get', mutatesAuthority: false },
  { method: 'GET', path: '/session/{sid}/summary', operationId: 'session_summary_session__sid__summary_get', mutatesAuthority: false },
  { method: 'POST', path: '/siteplan/analyze', operationId: 'siteplan_analyze_siteplan_analyze_post', mutatesAuthority: true },
  { method: 'POST', path: '/siteplan/volume', operationId: 'siteplan_volume_siteplan_volume_post', mutatesAuthority: true },
  { method: 'GET', path: '/sites', operationId: 'sites_list_sites_get', mutatesAuthority: false },
  { method: 'POST', path: '/slam', operationId: 'post_slam_slam_post', mutatesAuthority: true },
  { method: 'POST', path: '/slam/compare', operationId: 'post_slam_compare_slam_compare_post', mutatesAuthority: true },
  { method: 'POST', path: '/soil/{name}', operationId: 'soil_save_soil__name__post', mutatesAuthority: true },
  { method: 'GET', path: '/soils', operationId: 'soils_list_soils_get', mutatesAuthority: false },
  { method: 'GET', path: '/solar', operationId: 'solar_solar_get', mutatesAuthority: false },
  { method: 'POST', path: '/structure', operationId: 'post_structure_structure_post', mutatesAuthority: true },
  { method: 'GET', path: '/structures/custom', operationId: 'structure_list_structures_custom_get', mutatesAuthority: false },
  { method: 'DELETE', path: '/structures/custom/{name}', operationId: 'structure_delete_structures_custom__name__delete', mutatesAuthority: true },
  { method: 'POST', path: '/structures/custom/{name}', operationId: 'structure_save_structures_custom__name__post', mutatesAuthority: true },
  { method: 'GET', path: '/structures/custom/{name}/expand', operationId: 'structure_expand_structures_custom__name__expand_get', mutatesAuthority: false },
  { method: 'GET', path: '/tiles/{name}/{asset}', operationId: 'get_tile_tiles__name___asset__get', mutatesAuthority: false },
  { method: 'GET', path: '/trainer/history', operationId: 'trainer_history_trainer_history_get', mutatesAuthority: false },
  { method: 'GET', path: '/twin/cg', operationId: 'twin_cg_twin_cg_get', mutatesAuthority: false },
  { method: 'GET', path: '/twin/history', operationId: 'twin_history_twin_history_get', mutatesAuthority: false },
  { method: 'POST', path: '/twin/resync', operationId: 'twin_resync_twin_resync_post', mutatesAuthority: true },
  { method: 'GET', path: '/twin/terrain/{site}', operationId: 'twin_terrain_twin_terrain__site__get', mutatesAuthority: false },
  { method: 'POST', path: '/twin/terrain/{site}', operationId: 'twin_terrain_record_twin_terrain__site__post', mutatesAuthority: true },
  { method: 'GET', path: '/twin/version', operationId: 'twin_version_twin_version_get', mutatesAuthority: false },
  { method: 'GET', path: '/world', operationId: 'world_world_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/layer-catalog', operationId: 'layer_catalog_world_layer_catalog_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/layer-consumption', operationId: 'layer_consumption_world_layer_consumption_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/layer-manifest', operationId: 'world_layer_manifest_world_layer_manifest_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/point', operationId: 'world_point_world_point_get', mutatesAuthority: false },
  { method: 'POST', path: '/world/points', operationId: 'world_points_world_points_post', mutatesAuthority: true },
  { method: 'GET', path: '/world/site-markers', operationId: 'world_site_markers_world_site_markers_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/terrain_view', operationId: 'world_terrain_view_world_terrain_view_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/terrain_view.png', operationId: 'world_terrain_view_png_world_terrain_view_png_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/terramechanics-layers', operationId: 'terramechanics_layers_world_terramechanics_layers_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/traffic-layer', operationId: 'traffic_layer_world_traffic_layer_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/transaction', operationId: 'world_transaction_world_transaction_get', mutatesAuthority: false },
  { method: 'GET', path: '/world/transactions', operationId: 'world_transactions_world_transactions_get', mutatesAuthority: false },
  { method: 'POST', path: '/world/transect', operationId: 'world_transect_world_transect_post', mutatesAuthority: true },
  { method: 'GET', path: '/{path}', operationId: '_no_get__path__get', mutatesAuthority: false },
  { method: 'POST', path: '/{path}', operationId: '_no_post__path__post', mutatesAuthority: true },
];

/** Typed fetch against a known API route. Callers pass the STEWIE API key for mutations. */
export async function apiFetch<T = unknown>(
  route: ApiRoute, opts: { body?: unknown; apiKey?: string; signal?: AbortSignal } = {},
): Promise<T> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (opts.apiKey) headers['X-API-Key'] = opts.apiKey;
  const res = await fetch(route.path, {
    method: route.method, headers, signal: opts.signal,
    body: opts.body === undefined ? undefined : JSON.stringify(opts.body),
  });
  if (!res.ok) throw new Error(`${route.method} ${route.path} -> ${res.status}`);
  return (await res.json()) as T;
}
