#!/usr/bin/env python3
"""FS-23: the architecture-review traceability ledger.

A living, GENERATED map from each PRD §7 row to where it lives in the stack -- its backend
route(s), domain module(s), front-end adapter/view(s), test(s), and observability log wiring --
plus the list of links that are MISSING. It exposes those gaps WITHOUT implying the capability is
done: a row cited only by a test (no implementing route/module) or with no test at all is flagged
incomplete, so the ledger cannot read as "green" for a row that is only half-wired.

It is generated by SCANNING the live tree, never hand-maintained: it reuses req_trace's PRD §7
parser and the same [REQ:<ID>] marker convention, and additionally attributes bare row-id references
(e.g. a `# FS-10: latency budgets` header in a router/module) so implementation links surface even
where the code carries the id without the [REQ:] test-citation bracket. Every link is a real
file:line in the current checkout.

Usage: python3 scripts/arch_ledger.py [--prd PRD.md] [--json]
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)
import req_trace  # noqa: E402  -- reuse the PRD §7 parser + marker convention (not edited)

#: the code trees the ledger maps (the pytest testpaths + the served front-end assets + the deploy
#: manifests). PRD.md / docs at the repo root are excluded on purpose: a row id in the spec prose is not
#: an implementation link.
_CODE_ROOTS = ("stewie", "dart", "lode", "leap", "forge", "scripts", "ros2_ws", "deploy")
_REQ = re.compile(r"\[REQ:([A-Z]{2}-\d{2})\]")
_BARE = re.compile(r"\b([A-Z]{2}-\d{2})\b")
_LINK_KINDS = ("route", "module", "adapter", "test", "log")


def _is_test(path: str) -> bool:
    b = os.path.basename(path)
    return (b.startswith("test_") and b.endswith(".py")) or b.endswith(".test.js")


def _kind_for(path: str) -> str:
    """The link category a referencing file contributes (test wins, then route/adapter by location)."""
    if _is_test(path):
        return "test"
    norm = path.replace(os.sep, "/")
    if "/server/routers/" in norm:
        return "route"
    if "/web/assets/" in norm:
        return "adapter"
    return "module"


def _iter_source_files(repo: str):
    for root in _CODE_ROOTS:
        base = os.path.join(repo, root)
        if not os.path.isdir(base):
            continue
        for dirpath, dirs, files in os.walk(base):
            dirs[:] = [d for d in dirs if not d.startswith(".") and d not in ("__pycache__", "node_modules")]
            for fn in files:
                if fn.endswith((".py", ".js", ".html", ".yml", ".yaml", ".conf", ".md")):
                    yield os.path.join(dirpath, fn)


def scan_links(repo: str, row_ids: set) -> dict:
    """Scan the code tree once; per row id, collect its links keyed by kind -> [file:line]. A file that
    references the id AND writes to the observability ledger (log_event) also contributes a `log` link."""
    links: dict = {rid: {k: [] for k in _LINK_KINDS} for rid in row_ids}
    for path in _iter_source_files(repo):
        try:
            with open(path, encoding="utf-8", errors="replace") as f:
                lines = f.readlines()
        except OSError:
            continue
        text = "".join(lines)
        writes_log = ("log_event" in text) or ("log_audit" in text)
        kind = _kind_for(path)
        seen_here: set = set()
        rel = os.path.relpath(path, repo)
        for i, ln in enumerate(lines, 1):
            for m in list(_REQ.finditer(ln)) + list(_BARE.finditer(ln)):
                rid = m.group(1)
                if rid not in row_ids:
                    continue
                links[rid][kind].append(f"{rel}:{i}")
                if rid not in seen_here and not _is_test(path) and writes_log:
                    links[rid]["log"].append(rel)   # this row is observable via this file's ledger writes
                seen_here.add(rid)
    return links


def build_ledger(prd_path: str, repo: str | None = None) -> dict:
    """Per §7 row: {links by kind, missing kinds, incomplete}. A row is incomplete when it has no test
    (unverified) OR no implementation link at all (route/module/adapter) -- i.e. no route/test evidence."""
    repo = repo or os.path.dirname(_HERE)
    reqs = req_trace.parse_requirements(prd_path)
    links = scan_links(repo, set(reqs))
    ledger: dict = {}
    for rid, meta in reqs.items():
        kl = links.get(rid, {k: [] for k in _LINK_KINDS})
        missing = [k for k in _LINK_KINDS if not kl[k]]
        has_test = bool(kl["test"])
        has_impl = bool(kl["route"] or kl["module"] or kl["adapter"])
        ledger[rid] = {
            "pri": meta["pri"],
            "links": {k: kl[k] for k in _LINK_KINDS},
            "counts": {k: len(kl[k]) for k in _LINK_KINDS},
            "missing": missing,
            # exposed WITHOUT implying done: a row is complete-in-trace only when it is both wired
            # (>=1 implementation link) AND verified (>=1 test) -- never inferred from the PRD glyph.
            "incomplete": (not has_test) or (not has_impl),
        }
    return ledger


def summarize(ledger: dict) -> dict:
    total = len(ledger)
    incomplete = [r for r, d in ledger.items() if d["incomplete"]]
    return {"rows": total, "incomplete": len(incomplete),
            "traced": total - len(incomplete), "incomplete_ids": sorted(incomplete)}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--prd", default=os.path.join(os.path.dirname(_HERE), "PRD.md"))
    ap.add_argument("--json", action="store_true", help="emit the full ledger as JSON")
    args = ap.parse_args(argv)
    ledger = build_ledger(args.prd)
    if args.json:
        print(json.dumps(ledger, indent=2, sort_keys=True))
        return 0
    s = summarize(ledger)
    print(f"architecture ledger: {s['rows']} rows, {s['traced']} traced, {s['incomplete']} incomplete")
    for rid in sorted(ledger):
        d = ledger[rid]
        c = d["counts"]
        flag = "INCOMPLETE" if d["incomplete"] else "traced"
        miss = (" missing=" + ",".join(d["missing"])) if d["missing"] else ""
        print(f"  {rid} [{flag}] route={c['route']} module={c['module']} adapter={c['adapter']} "
              f"test={c['test']} log={c['log']}{miss}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
