"""[REQ:BA-04] Generate a Gazebo heightfield world from the REAL Haworth lunar DEM.

Replaces the flat regolith plane in the sim: crops a 2^n+1 window of the LOLA 5 m DEM (centered, so the
work-site relief is present), writes a grayscale heightmap PNG + a world SDF whose terrain geometry is
that heightmap. No fabricated terrain -- the heightmap IS the DEM. gz-sim reads an 8-bit grayscale
heightmap of side 2^n+1 and stretches it over `<size> x y z </size>` metres (z = the DEM relief).

CLI: python -m scripts.dem_to_gazebo_heightfield [out_dir]
"""
from __future__ import annotations

import math
import os
import sys

import numpy as np
from PIL import Image

from stewie.terrain.site_dem import load_haworth_dem

_N = 513  # 2^9 + 1 (gz heightmap LOD needs a 2^k+1 square)


def _pow2_plus_1(n: int) -> int:
    """Largest 2^k+1 that fits in n."""
    return (1 << int(math.log2(max(n - 1, 2)))) + 1


def _world_sdf(size_x: float, size_y: float, relief: float, heightmap_uri: str) -> str:
    z = max(relief, 0.1)
    return f"""<?xml version="1.0"?>
<!-- [REQ:BA-04] GENERATED by scripts/dem_to_gazebo_heightfield.py from the real Haworth LOLA DEM.
     Lunar gravity + low sun + the gz systems the bridge depends on; the terrain is the DEM heightmap
     (NOT a flat plane). Regenerate; do not hand-edit. -->
<sdf version="1.9">
  <world name="stewie_lunar">
    <gravity>0 0 -1.62</gravity>
    <physics name="1ms" type="ignored"><max_step_size>0.001</max_step_size></physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows><direction>0.5 0.2 -0.85</direction>
      <diffuse>1 1 1 1</diffuse><specular>0.3 0.3 0.3 1</specular>
    </light>
    <model name="haworth_terrain">
      <static>true</static>
      <link name="surface">
        <collision name="collision">
          <geometry><heightmap>
            <uri>{heightmap_uri}</uri>
            <size>{size_x:.3f} {size_y:.3f} {z:.3f}</size>
            <pos>0 0 0</pos>
          </heightmap></geometry>
        </collision>
        <visual name="visual">
          <geometry><heightmap>
            <uri>{heightmap_uri}</uri>
            <size>{size_x:.3f} {size_y:.3f} {z:.3f}</size>
            <pos>0 0 0</pos>
          </heightmap></geometry>
          <material><ambient>0.25 0.25 0.25 1</ambient><diffuse>0.35 0.35 0.35 1</diffuse></material>
        </visual>
      </link>
    </model>
  </world>
</sdf>
"""


def build_heightfield(out_dir: str, *, n: int = _N, bundle_dir: str | None = None) -> dict:
    """Crop -> normalize -> write heightmap.png + haworth_heightfield.sdf. Returns the provenance dict."""
    Z, cell = load_haworth_dem(bundle_dir)
    H, W = Z.shape
    n = _pow2_plus_1(min(n, H, W))
    r0, c0 = (H - n) // 2, (W - n) // 2
    win = np.asarray(Z[r0:r0 + n, c0:c0 + n], dtype=np.float64)
    zmin, zmax = float(win.min()), float(win.max())
    relief = zmax - zmin
    norm = ((win - zmin) / (relief if relief > 0 else 1.0) * 255.0).round().astype(np.uint8)
    os.makedirs(out_dir, exist_ok=True)
    png = os.path.join(out_dir, "heightmap.png")
    Image.fromarray(norm, mode="L").save(png)
    size_x = size_y = float(n * cell)
    world = os.path.join(out_dir, "haworth_heightfield.sdf")
    with open(world, "w", encoding="utf-8") as fh:
        fh.write(_world_sdf(size_x, size_y, relief, "heightmap.png"))
    return {"png": png, "world": world, "n": n, "cell_m": cell, "relief_m": relief,
            "size_m": (size_x, size_y, relief), "z_range_m": (zmin, zmax)}


def main(argv=None) -> int:
    a = argv if argv is not None else sys.argv[1:]
    out = a[0] if a else os.path.join(os.path.dirname(__file__), "..", "ros2_ws",
                                      "src", "stewie_description", "worlds")
    rec = build_heightfield(os.path.abspath(out))
    print(f"wrote {rec['world']} + {rec['png']}: {rec['n']}x{rec['n']} @ {rec['cell_m']:g} m, "
          f"relief {rec['relief_m']:.1f} m, extent {rec['size_m'][0]:.0f} m")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
