"""[REQ:AC-01] Generate a TypeScript API client from the live FastAPI OpenAPI, with NO npm toolchain -- a
deterministic Python codegen writing one committed `.ts`. The client is the typed contract the migrating
cockpit panes bind to (ADR-0007 strangler-fig): every router-owned route becomes a typed entry, so a route
added/removed/renamed on the FastAPI side makes the committed client DRIFT and the CI check reds until it is
regenerated. Run: `python scripts/gen_ts_api_client.py` (writes) or `--check` (reds on drift, for CI).

The client is intentionally minimal + framework-agnostic (works from vanilla JS today and any React shell
later): a typed route table + a typed `apiFetch`. It does NOT hand-roll TS types for every schema (that is a
generator-library concern deferred with the React-stack decision); it binds the ROUTE surface, which is what
drifts and what the route registry (AC-02) annotates.
"""
from __future__ import annotations

import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_REL = "stewie/server/web/assets/api_client.ts"
_OUT = os.path.join(_ROOT, _REL)
_METHODS = ("get", "post", "put", "delete", "patch")
_HEADER = "// GENERATED by scripts/gen_ts_api_client.py from the FastAPI OpenAPI -- DO NOT EDIT BY HAND.\n" \
          "// Regenerate with `python scripts/gen_ts_api_client.py`; CI (--check) reds on drift.\n"


def _routes_from_openapi(spec: dict) -> list[dict]:
    """Every non-exempt (method, path) API operation in the OpenAPI, as a sorted deterministic list. Static /
    doc / SPA-serving routes (/, /app, /docs, ...) are excluded -- the typed client is the API surface, and
    excluding them keeps the client stable when a static route (like the /app SPA fallback) is added."""
    from stewie.server.route_registry import is_exempt

    out = []
    for path, ops in spec.get("paths", {}).items():
        if is_exempt(path):
            continue
        for method, op in ops.items():
            if method not in _METHODS:
                continue
            out.append({
                "method": method.upper(),
                "path": path,
                "operationId": op.get("operationId", ""),
                "mutates": method in ("post", "put", "delete", "patch"),
            })
    return sorted(out, key=lambda r: (r["path"], r["method"]))


def render(spec: dict) -> str:
    """Render the deterministic TypeScript client source from an OpenAPI spec dict."""
    routes = _routes_from_openapi(spec)
    paths = sorted({r["path"] for r in routes})
    lines = [_HEADER, ""]
    lines.append("export type ApiPath =")
    lines += [f"  | {p!r}" for p in paths]
    lines[-1] += ";"
    lines.append("")
    lines.append("export interface ApiRoute {")
    lines.append("  readonly method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';")
    lines.append("  readonly path: ApiPath;")
    lines.append("  readonly operationId: string;")
    lines.append("  readonly mutatesAuthority: boolean;")
    lines.append("}")
    lines.append("")
    lines.append("export const API_ROUTES: readonly ApiRoute[] = [")
    for r in routes:
        lines.append(
            f"  {{ method: {r['method']!r}, path: {r['path']!r}, "
            f"operationId: {r['operationId']!r}, mutatesAuthority: {str(r['mutates']).lower()} }},")
    lines.append("];")
    lines.append("")
    lines.append("/** Typed fetch against a known API route. Callers pass the STEWIE API key for mutations. */")
    lines.append("export async function apiFetch<T = unknown>(")
    lines.append("  route: ApiRoute, opts: { body?: unknown; apiKey?: string; signal?: AbortSignal } = {},")
    lines.append("): Promise<T> {")
    lines.append("  const headers: Record<string, string> = { 'Content-Type': 'application/json' };")
    lines.append("  if (opts.apiKey) headers['X-API-Key'] = opts.apiKey;")
    lines.append("  const res = await fetch(route.path, {")
    lines.append("    method: route.method, headers, signal: opts.signal,")
    lines.append("    body: opts.body === undefined ? undefined : JSON.stringify(opts.body),")
    lines.append("  });")
    lines.append("  if (!res.ok) throw new Error(`${route.method} ${route.path} -> ${res.status}`);")
    lines.append("  return (await res.json()) as T;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _live_spec() -> dict:
    from stewie.server.server import app
    return app.openapi()


def main(argv: list[str]) -> int:
    src = render(_live_spec())
    if "--check" in argv:
        try:
            with open(_OUT, encoding="utf-8") as fh:
                committed = fh.read()
        except OSError:
            committed = ""
        if committed != src:
            print(f"DRIFT: {_REL} is stale vs the FastAPI OpenAPI. Run: python scripts/gen_ts_api_client.py")
            return 1
        print(f"{_REL} is in sync with the FastAPI OpenAPI.")
        return 0
    with open(_OUT, "w", encoding="utf-8") as fh:
        fh.write(src)
    print(f"wrote {_REL} ({src.count('method:')} routes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
