"""OPS-03 (PRD §27.2.A / PO-05) — acceptance test for the SBOM generator.

`scripts/gen_sbom.py` emits a CycloneDX 1.5 JSON SBOM from the REAL pinned dependency lock
(`requirements-*.lock`, generated by `uv pip compile`). No fabricated components: every component
in the SBOM is a package actually present in the lock, with its pinned version and pinned hashes.
This test exercises the generator end-to-end against the checked-in lock files.

[REQ:PO-05]
"""
from __future__ import annotations

import importlib.util
import json
import os

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SBOM = os.path.join(_ROOT, "scripts", "gen_sbom.py")
_DEV_LOCK = os.path.join(_ROOT, "requirements-dev.lock")
_SERVER_LOCK = os.path.join(_ROOT, "requirements-server.lock")


def _load_module():
    import sys
    spec = importlib.util.spec_from_file_location("gen_sbom", _SBOM)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod   # so dataclasses can resolve cls.__module__ under PEP 563
    spec.loader.exec_module(mod)
    return mod


def test_parse_lock_returns_real_pinned_packages():
    mod = _load_module()
    pkgs = mod.parse_lock(_DEV_LOCK)
    names = {p.name for p in pkgs}
    # real, known entries from the checked-in dev lock
    assert "numpy" in names
    assert "gymnasium" in names
    assert "pytest" in names
    # every parsed package carries a pinned version (==), no ranges
    for p in pkgs:
        assert p.version and all(c not in p.version for c in "<>~ ,")
    # hashes are captured from the lock (--generate-hashes)
    assert any(p.hashes for p in pkgs), "expected at least one package with pinned hashes"


def test_parse_lock_normalizes_names_and_dedups():
    mod = _load_module()
    pkgs = mod.parse_lock(_DEV_LOCK)
    names = [p.name for p in pkgs]
    assert len(names) == len(set(names)), "duplicate component names in SBOM source"
    # PEP 503 normalization: lowercase, no underscores leaking as distinct keys
    assert all(n == n.lower() for n in names)


def test_build_sbom_is_valid_cyclonedx():
    mod = _load_module()
    pkgs = mod.parse_lock(_DEV_LOCK)
    doc = mod.build_sbom(pkgs, source_name="requirements-dev.lock")
    assert doc["bomFormat"] == "CycloneDX"
    assert doc["specVersion"] == "1.5"
    assert doc["version"] == 1
    assert "serialNumber" in doc and doc["serialNumber"].startswith("urn:uuid:")
    md = doc["metadata"]
    assert md["component"]["name"] == "stewie"
    # tools recorded so the SBOM is self-describing
    assert any(t.get("name") == "gen_sbom" for t in md["tools"]["components"]), md["tools"]
    comps = doc["components"]
    assert len(comps) == len(pkgs)
    for c, p in zip(sorted(comps, key=lambda x: x["name"]), sorted(pkgs, key=lambda x: x.name)):
        assert c["type"] == "library"
        assert c["name"] == p.name
        assert c["version"] == p.version
        assert c["purl"] == f"pkg:pypi/{p.name}@{p.version}"
        assert c["bom-ref"] == c["purl"]
        if p.hashes:
            algs = {h["alg"] for h in c["hashes"]}
            assert algs == {"SHA-256"}


def test_build_sbom_components_are_unique_refs():
    mod = _load_module()
    pkgs = mod.parse_lock(_SERVER_LOCK)
    doc = mod.build_sbom(pkgs, source_name="requirements-server.lock")
    refs = [c["bom-ref"] for c in doc["components"]]
    assert len(refs) == len(set(refs)), "duplicate bom-ref"


def test_main_writes_json_to_disk(tmp_path):
    mod = _load_module()
    out = tmp_path / "sbom.json"
    rc = mod.main(["--lock", _DEV_LOCK, "--name", "requirements-dev.lock", "-o", str(out)])
    assert rc == 0
    doc = json.loads(out.read_text())
    assert doc["bomFormat"] == "CycloneDX"
    assert doc["components"], "empty SBOM"


def test_sbom_covers_both_locks_with_no_fabricated_components():
    """Cross-check: every SBOM component name appears verbatim in the source lock (no invented pkgs)."""
    mod = _load_module()
    for lock in (_DEV_LOCK, _SERVER_LOCK):
        raw = open(lock).read().lower()
        doc = mod.build_sbom(mod.parse_lock(lock), source_name=os.path.basename(lock))
        for c in doc["components"]:
            assert c["name"] in raw, f"{c['name']} not in {lock} (fabricated component)"
