"""OPS-03 (PRD §27.2.A / PO-05) — fresh-install smoke for the dependency LOCK.

Distinct from `stewie/server/test_fresh_wheel.py` (which builds the wheel and installs the `[server]`
EXTRA). This smoke targets the pinned LOCK file itself: it proves the lock's resolved, hash-pinned
package set is internally consistent and installable, and that the currently-resolved environment
matches the lock (the always-on fast mode). The slow real clean-venv install from the lock is opt-in
(STEWIE_LOCK_SMOKE=1; network + ~min).

[REQ:PO-05]
"""
from __future__ import annotations

import importlib.util
import os

import pytest

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SMOKE = os.path.join(_ROOT, "scripts", "fresh_install_smoke.py")
_DEV_LOCK = os.path.join(_ROOT, "requirements-dev.lock")
_SERVER_LOCK = os.path.join(_ROOT, "requirements-server.lock")


def _load_module():
    import sys
    spec = importlib.util.spec_from_file_location("fresh_install_smoke", _SMOKE)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod   # so dataclasses can resolve cls.__module__ under PEP 563
    spec.loader.exec_module(mod)
    return mod


def test_lock_is_fully_hash_pinned():
    """A lock generated by `uv pip compile --generate-hashes` must hash-pin every component."""
    mod = _load_module()
    report = mod.audit_lock(_DEV_LOCK)
    assert report.total > 0
    # every pinned package carries at least one sha256 hash (no unpinned artifact slips through)
    assert report.unhashed == [], f"unhashed packages in lock: {report.unhashed}"


def test_installed_env_covers_dev_lock():
    """The resolved env must have every lock package installed (no totally-missing package).

    Version drift (a newer point release than the lock pins) is environment-dependent — a freshly
    `uv pip install -e .[dev]` resolves newer releases than a hash-pinned CI install from the lock —
    so it is surfaced (`mismatched`), not asserted to zero here. The `--strict` CLI path (CI, which
    installs FROM the lock) is what gates on drift; this test gates on completeness.
    """
    mod = _load_module()
    result = mod.verify_installed(_DEV_LOCK)
    assert result.checked > 0
    assert result.missing == [], f"declared-in-lock but not installed at all: {result.missing}"


def test_server_lock_audit_is_clean():
    mod = _load_module()
    report = mod.audit_lock(_SERVER_LOCK)
    assert report.total > 0
    assert report.unhashed == []


def test_main_fast_mode_passes():
    mod = _load_module()
    rc = mod.main(["--lock", _DEV_LOCK])
    assert rc == 0


@pytest.mark.skipif(os.environ.get("STEWIE_LOCK_SMOKE") != "1",
                    reason="real clean-venv lock install is opt-in (network + slow)")
def test_real_clean_install_from_lock(tmp_path):
    mod = _load_module()
    rc = mod.clean_install(_DEV_LOCK, str(tmp_path / "venv"))
    assert rc == 0
